# Generated by Django 4.1 on 2022-08-25 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_classlist_classroomlayout"),
    ]

    operations = [
        migrations.AddField(
            model_name="classlist",
            name="name",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="classroomlayout",
            name="name",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
